# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed5589c9358f3ca4ddc7956df9781523a9211b1cc9a5bfc3d2c99ae199bffffa16c4024236246832e0da751c87aedd450bf92d099cd670611def66a7d9d5bacd

test:
  secret_key_base: 1b6b82e8f58781d5a397ad10fa4a28527b59ff4696714a3b19837eb221a27831464158fbb6fc201f9834b99af44c77132b727867f457b8e9c40f68745fa351e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
